apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ladama
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: registry.gitlab.com/beninfcrb/ladama:06978a64
        # imagePullPolicy: Never
        ports:
        - containerPort: 80
